describe('Farm Tests', () => {
    // Pre Condition
    beforeEach(() => {
        // Log In
        cy.visit('https://gulfarms.herokuapp.com')
        cy.get('#email').type('mjunaid.s100@gmail.com')
        cy.get('#password').type('123456789{enter}')
        cy.wait(2000)
        cy.contains('Farms').click()
    })
    it('Test for Creating New Farm with VALID inputs', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.get('#farmName').type('farm1').should('have.value', 'farm1')
        cy.get('#Location').type('Lahore').should('have.value', 'Lahore')
        cy.get('#Description').type('Newly Created for test').should('have.value', 'Newly Created for test')
        cy.get('#AlertDescription').type('Clean').should('have.value', 'Clean')
        cy.get('#AlertDuration').type('2').should('have.value', '2')
        cy.get('.fa-plus').click()
        cy.contains('SAVE').click()
        cy.wait(1000)
        cy.contains('farm1')
    })
    it('Test for display of errors for the required fields', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.contains('SAVE').click()
        cy.contains('Name and Location are required')
    })
    it('Test for Creating New Farm with INVALID inputs', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.get('#farmName').type('farm2').should('have.value', 'farm2')
        cy.get('#Location').type('Lahore').should('have.value', 'Lahore')
        cy.get('#Description').type('Newly Created for test').should('have.value', 'Newly Created for test')
        cy.get('.fa-plus').click()
        cy.contains('SAVE').click()
        cy.wait(1000)
        cy.contains('farm2').should('not.exist')
    })
    it('Test for Deleting Farm', () => {
        cy.wait(1000)
        cy.contains('farm2').click()
        cy.wait(1000)
        cy.get('.fa-trash-alt').click()
        cy.contains('Reason For Removal')
        cy.contains('Save').click()
        cy.wait(1000)
        cy.url().should('have', '/farms')
        cy.wait(2000)
        cy.contains('farm2').should('not.exist')
    })
})
