describe('Finance Tests', () => {
    // Pre Condition
    beforeEach(() => {
        // Log In
        cy.visit('https://gulfarms.herokuapp.com')
        cy.get('#email').type('mjunaid.s100@gmail.com')
        cy.get('#password').type('123456789{enter}')
        cy.wait(2000)
        cy.contains('Finance').click()
    })
    it('Test to Add Earning', () => {
        cy.wait(1000)
        cy.get('#eDesc').type('wool')
        cy.get('#eAmount').type('1000')
        cy.get('#eQuantity').type('10')
        cy.get('#eUnit').type('kg')
        cy.get('.fin-button').click({multiple: true})
        cy.contains('wool')
    })
    it('Test to Add Expenditures', () => {
        cy.wait(1000)
        cy.get('#exDesc').type('school')
        cy.get('#exAmount').type('1000')
        cy.get('#exQuantity').type('10')
        cy.get('#exUnit').type('kg')
        cy.get('.fin-button').click({multiple: true})
        cy.contains('school')
    })
    it('Test for INVALID Inputs', () => {
        cy.wait(1000)
        cy.get('#exDesc').type('test11')
        cy.get('#exAmount').type('ss')
        cy.get('#exQuantity').type('ss')
        cy.get('#exUnit').type('kg')
        cy.get('#eDesc').type('test22')
        cy.get('#eAmount').type('ss')
        cy.get('#eQuantity').type('ss')
        cy.get('#eUnit').type('kg')
        cy.get('.fin-button').click({multiple: true})
        cy.contains('test11').should('not.exist')
        cy.contains('test21').should('not.exist')
    })
    it('Test for Correct Calculation of Income', () => {
        cy.wait(1000)
        cy.get('.fa-times').click({multiple: true})
        cy.get('#exDesc').type('test1')
        cy.get('#exAmount').type('10000')
        cy.get('#exQuantity').type('10')
        cy.get('#exUnit').type('kg')
        cy.get('#eDesc').type('test2')
        cy.get('#eAmount').type('15000')
        cy.get('#eQuantity').type('20')
        cy.get('#eUnit').type('kg')
        cy.get('.fin-button').click({multiple: true})
        cy.wait(2000)
        cy.contains('5000')
    })
    it('Test to Remove All Finances', () => {
        cy.wait(1000)
        cy.get('.fa-times').click({multiple: true})
        cy.wait(2000)
        cy.contains('.fin-net-quantity', '0')
    })
})