describe('Preset Tests', () => {
    // Pre Condition
    beforeEach(() => {
        // Log In
        cy.visit('https://gulfarms.herokuapp.com')
        cy.get('#email').type('mjunaid.s100@gmail.com')
        cy.get('#password').type('123456789{enter}')
        cy.wait(2000)
        cy.contains('Farms').click()
        cy.wait(500)
        cy.contains('farm1').click()
    })
    it('Test for Creating New Animal Preset with VALID inputs', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.get('#AnimalName').type('preset1').should('have.value', 'preset1')
        cy.get('#CheckBox').click()
        cy.get('#FieldName').type('id').should('have.value', 'id')
        cy.contains('String').click()
        cy.contains('String').click()
        cy.get('#ProductDescription').type('Milk').should('have.value', 'Milk')
        cy.get('#ProductDuration').type('2').should('have.value', '2')
        cy.get('.fa-plus').click({multiple: true})
        cy.get('#recordParents').click()
        cy.get('#recordOffspring').click()
        cy.get('#AlertDuration').type('1').should('have.value', '1')
        cy.contains('SAVE').click()
        cy.wait(1000)
        cy.contains('preset1')
    })
    it('Test for display of errors for the required fields', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.contains('SAVE').click()
        cy.contains('Name is required')
    })
    it('Test for Creating New Animal Preset with INVALID inputs', () => {
        cy.wait(1000)
        cy.get('.fa-plus-circle').click()
        cy.get('#AnimalName').type('preset2').should('have.value', 'preset2')
        cy.get('#FieldName').type('id').should('have.value', 'id')
        cy.get('#ProductDescription').type('Milk').should('have.value', 'Milk')
        cy.get('#ProductDuration').type('ss').should('have.value', 'ss')
        cy.get('.fa-plus').click({multiple: true})
        cy.get('#recordOffspring').click()
        cy.contains('SAVE').click()
        cy.wait(1000)
        cy.contains('Error Invalid Inputs')
    })
    it('Test for Deleting Animal Preset', () => {
        cy.wait(1000)
        cy.contains('preset2').click()
        cy.wait(1000)
        cy.get('.fa-trash-alt').click()
        cy.contains('Reason For Removal')
        cy.contains('Save').click()
        cy.wait(1000)
        cy.url().should('have', '/farms')
        cy.contains('farm1').click()
        cy.wait(1000)
        cy.contains('preset2').should('not.exist')
    })
})