export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGGED ="SET_AUTHENTICATION"
export const GET_FARMS="GET_FARMS"
export const SET_FARMS="SET_FARMS"
export const SET_DETAIL_FARM="SET_DETAIL_FARM"
export const SET_FARM="SET_FARM"  
export const SET_PRESET= "SET_PRESET" 
export const SET_PRESETS= "SET_PRESETs" 